baseURL: "https://wxiang.cc/"
theme: LoveIt

title: 须远
timeZone: "Asia/Shanghai"

languageCode: zh-CN
defaultContentLanguage: zh-cn
disableLanguages: en

googleAnalytics: G-925QSPB2XF
disqusShortname: wxiang

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  category: categories
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
