baseURL: "https://wxiang.cc/"
theme:
  - PaperMod
  # - LoveIt
languageCode: zh-CN
defaultContentLanguage: zh-cn
disableLanguages:
  - en

googleAnalytics: G-925QSPB2XF
disqusShortname: wxiang

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

markup:
  highlight:
    noClasses: false
