baseURL: "https://wxiang.cc/"
languageCode: zh-CN
disableLanguages: en
defaultContentLanguage: zh-cn
timeZone: "Asia/Shanghai"
theme: LoveIt
title: 须远

enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
author:
  name: 须远
  email: itwangxiang@gmail.com
  link: https://wxiang.cc/about
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: :filename
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML




googleAnalytics: G-925QSPB2XF
disqusShortname: wxiang
