main:
  - identifier: "posts"
    name: posts
    url: /posts/
    weight: 1
  - identifier: "search"
    name: search
    url: /search/
    weight: 2
  - identifier: "tags"
    name: tags
    url: /tags/
    weight: 3
  - identifier: "categories"
    name: categories
    url: /categories/
    weight: 4
