main:
  - identifier: "posts"
    name: 文章
    url: /posts/
    weight: 10
  - identifier: "tags"
    name: 标签
    url: /tags/
    weight: 20
  - identifier: "categories"
    name: 分类
    url: /categories/
    weight: 30
  - identifier: "about"
    name: 关于
    url: /about/
    weight: 40
