version: 0.2.X
defaultTheme: auto
gitRepo: "https://github.com/itwangxiang/itwangxiang.github.io"
fingerprint: ""
dateFormat: "2006-01-02"
editPost:
  url: "https://github.com/itwangxiang/itwangxiang.github.io/tree/master/content"
  text: "编辑" # edit text
  appendFilePath: true # to append file path to Edit link
search:
  enable: true
  type: lunr
  contentLength: 4000
  placeholder: ""
  maxResultLength: 10
  snippetLength: 50
  highlightTag: em
  absoluteURL: false
  algolia:
    index: ""
    appID: ""
    searchKey: ""
images:
  - /logo.jpg
header:
  desktopMode: fixed
  mobileMode: auto
  title:
    logo: ""
    name: 须远
    pre: ""
    post: ""
    typeit: false
footer:
  enable: true
  custom: "wxiang.cc"
  hugo: false
  copyright: true
  author: true
  since: 2015
section:
  paginate: 20
  dateFormat: 01-02
  rss: 10
list:
  paginate: 20
  dateFormat: 01-02
  rss: 10
page:
  hiddenFromHomePage: false
  hiddenFromSearch: false
  twemoji: false
  lightgallery: false
  ruby: true
  fraction: true
  fontawesome: true
  linkToMarkdown: true
  rssFullText: false
  toc:
    enable: true
    keepStatic: false
    auto: true
  code:
    copy: true
    maxShownLines: 10
  math:
    enable: false
    blockLeftDelimiter: ""
    blockRightDelimiter: ""
    inlineLeftDelimiter: ""
    inlineRightDelimiter: ""
    copyTex: true
    mhchem: true
  share:
    enable: true
    Twitter: true
    Facebook: true
    Linkedin: false
    Whatsapp: false
    Pinterest: false
    Tumblr: false
    HackerNews: false
    Reddit: false
    VK: false
    Buffer: false
    Xing: false
    Line: true
    Instapaper: false
    Pocket: false
    Digg: false
    Stumbleupon: false
    Flipboard: false
    Weibo: true
    Renren: false
    Myspace: false
    Blogger: false
    Baidu: false
    Odnoklassniki: false
    Evernote: false
    Skype: false
    Trello: false
    Mix: false
  comment:
    enable: true
    disqus:
      enable: true
      shortname: "wxiang"
    gitalk:
      enable: false
      owner: ""
      repo: ""
      clientId: ""
      clientSecret: ""
    valine:
      enable: false
      appId: ""
      appKey: ""
      placeholder: ""
      avatar: mp
      meta: ""
      pageSize: 10
      lang: ""
      visitor: true
      recordIP: true
      highlight: true
      enableQQ: false
      serverURLs: "https://leancloud.hugoloveit.com"
      emoji: ""
    facebook:
      enable: false
      width: 100%
      numPosts: 10
      appId: ""
      languageCode: ""
    telegram:
      enable: false
      siteID: ""
      limit: 5
      height: ""
      color: ""
      colorful: true
      dislikes: false
      outlined: false
    commento:
      enable: false
    utterances:
      enable: false
      repo: ""
      issueTerm: pathname
      label: ""
      lightTheme: github-light
      darkTheme: github-dark
  library:
    css: {}
    js: {}
  seo:
    images: []
    publisher:
      name: 须远
      logoUrl: /images/avatar.png
home:
  rss: 10
  profile:
    enable: true
    avatarURL: "./logo.jpg"
    title: "人生当立志，立志须高远"
    subtitle: "欢迎来到我的个人小站"
    typeit: true
    social: true
    disclaimer:
  posts:
    enable: true
    paginate: 6
    defaultHiddenFromHomePage: false
social:
  Github: itwangxiang
  RSS: true
  Email: itwangxiang@gmail.com
typeit:
  speed: 100
  cursorSpeed: 1000
  cursorChar: "|"
  duration: -1
verification:
  google: ""
  bing: ""
  yandex: ""
  pinterest: ""
  baidu: ""
seo:
  image: /logo.jpg
  thumbnailUrl: /logo.jpg
analytics:
  enable: false
  google:
    id: "G-925QSPB2XF"
    anonymizeIP: true
  fathom:
    id: ""
    server: ""
cookieconsent:
  enable: false
  content:
    message: ""
    dismiss: ""
    link: ""
cdn:
  data: jsdelivr.yml
compatibility:
  polyfill: false
  objectFit: false