baseURL: "https://wxiang.cc/"
title: 须远
paginate: 5
theme:
  - PaperMod

params:
  env: production
  description: "Kim 个人博客 - https://github.com/itwangxiang/blog"
  author: Kim Liss
  homeInfoParams:
    Title: "人生当立志，立志须高远"
    Content: >
      欢迎来到我的个人博客

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: true
  images: []

  socialIcons:
    - name: github
      url: "https://github.com/itwangxiang"
    - name: RsS
      url: "index.xml"
    - name: email
      url: "mailto:itwangxiang@gmail.com"

  editPost:
    URL: "https://github.com/itwangxiang/itwangxiang.github.io/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

defaultContentLanguage: zh
languages:
  zh:
    timeZone: "Asia/Shanghai"
    dateFormat: "2006年01月02日"
    profileMode:
      enabled: true
      title: 人生当立志，立志须高远
      subtitle: "欢迎来到我的个人小站"
      imageUrl: "https://avatars.githubusercontent.com/u/7286154"
      imageTitle: 头像
      imageWidth: 120
      imageHeight: 120
      buttons:
        - name: 博客
          url: coding
        - name: 标签
          url: tags
    menu:
      main:
        - name: 目录
          url: archives
          weight: 5
        - name: 搜索
          url: search/
          weight: 10
        - name: 标签
          url: tags/
          weight: 10
        - name: 分类
          url: categories/
          weight: 10

googleAnalytics: G-925QSPB2XF
disqusShortname: wxiang

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true

privacy:
  vimeo:
    disabled: true
    simple: true

  twitter:
    disabled: true
    enableDNT: true
    simple: true

  instagram:
    disabled: true
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
